apiVersion: apps/v1
kind: Deployment
metadata:
  name: movies-suggester
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movies-suggester
  template:
    metadata:
      labels:
        app: movies-suggester
    spec:
      containers:
        - name: go-app-container
          image: tomaslingotti/movies-suggester
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 3001
---
apiVersion: v1
kind: Service                    # Type of kubernetes resource
metadata:
  name: movies-suggester-service   # Name of the resource
spec:
  type: NodePort                 # A port is opened on each node in your cluster via Kube proxy.
  ports:                         # Take incoming HTTP requests on port 9090 and forward them to the targetPort of 8080
    - name: http
      port: 9090
      targetPort: 3001
  selector:
    app: movies-suggester         # Map any pod with label `app=movies-suggester` to this service